# Generated by Django 5.2.1 on 2025-05-27 03:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interno', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='ID Interno: solo mayúsculas, guiones y números.', regex='^[A-Z0-9-]+$')])),
                ('rfc', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='RFC: solo mayúsculas y números.', regex='^[A-Z0-9]+$')])),
                ('nombre_legal', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Nombre legal: solo letras y espacios.', regex='^[A-Za-z ]+$')])),
                ('datos_fiscales', models.TextField(validators=[django.core.validators.RegexValidator(message='Datos fiscales: solo letras, números, puntos y punto y coma.', regex='^[A-Za-z0-9.; ]+$')])),
                ('contacto_nombre', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Nombre legal: solo letras y espacios.', regex='^[A-Za-z ]+$')])),
                ('contacto_correo', models.EmailField(max_length=254, validators=[django.core.validators.RegexValidator(message='Correo: solo minúsculas, números, puntos y arroba.', regex='^[a-z0-9\\.]+@[a-z0-9\\.]+$')])),
                ('contacto_telefono', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Teléfono: debe tener 10 dígitos.', regex='^[0-9]{10}$')])),
                ('condiciones_pago', models.CharField(choices=[('Credito', 'Crédito'), ('Contado', 'Contado')], max_length=10)),
                ('clabe', models.CharField(max_length=18, validators=[django.core.validators.RegexValidator(message='CLABE: debe tener 18 dígitos.', regex='^[0-9]{18}$')])),
                ('tiempo_entrega', models.IntegerField(choices=[(1, '1 día'), (2, '2 días'), (3, '3 días'), (4, '4 días'), (5, '5 días'), (6, '6 días'), (7, '7 días'), (8, '8 días')])),
                ('cobertura', models.TextField(validators=[django.core.validators.RegexValidator(message='Cobertura: solo mayúsculas, números y punto y coma.', regex='^[A-Z0-9; ]+$')])),
                ('certificaciones', models.TextField(validators=[django.core.validators.RegexValidator(message='Certificaciones: solo mayúsculas, números y punto y coma.', regex='^[A-Z0-9; ]+$')])),
                ('rating_calidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rating_puntualidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rating_precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rating_promedio', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
            ],
        ),
    ]
