# Generated by Django 5.2.1 on 2025-05-27 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo7', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compuesto', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='modulo7.provider')),
            ],
        ),
    ]
