# Generated by Django 5.2.1 on 2025-05-28 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo7', '0003_pedido_canastaitem_pedidoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='modulo7.provider'),
        ),
    ]
