# Generated by Django 5.2.1 on 2025-05-28 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo7', '0004_pedido_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total acumulado de los precios de todos los compuestos', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='provider',
            field=models.ForeignKey(blank=True, help_text='Proveedor elegido según criterios', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='modulo7.provider'),
        ),
    ]
