# Generated by Django 5.2.1 on 2025-06-03 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo7', '0005_pedido_total_price_alter_pedido_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PEN', 'Pendiente'), ('ENV', 'Enviado'), ('FIN', 'Finalizado'), ('CAN', 'Cancelado')], default='PEN', help_text='Estado actual del pedido', max_length=3),
        ),
    ]
