# Generated by Django 5.2.1 on 2025-05-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compuesto', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('Generico', 'Genérico'), ('Patente', 'Patente')], max_length=8)),
                ('numero_serie', models.IntegerField()),
                ('cantidad', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Inventarios',
                'unique_together': {('compuesto', 'categoria')},
            },
        ),
    ]
