# Generated by Django 5.2.1 on 2025-05-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo5', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compuesto', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('Generico', 'Genérico'), ('Patente', 'Patente')], max_length=8)),
                ('numero_serie', models.IntegerField()),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'unique_together': {('compuesto', 'categoria')},
            },
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
    ]
