# Generated by Django 5.2.1 on 2025-05-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo5', '0002_item_delete_inventario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compuesto', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('Generico', 'Genérico'), ('Patente', 'Patente')], max_length=20)),
                ('numero_serie', models.IntegerField(unique=True)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
