# Generated by Django 5.2.1 on 2025-05-18 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo5', '0003_medicamento_delete_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='numero_serie',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='medicamento',
            unique_together={('compuesto', 'numero_serie')},
        ),
    ]
